### ISSUE TITLE
(Possible) explanation

### ISSUE THREAD

**Issue by jgierer12** [kentcdodds/ts-emotion-border-top-style-issue#2]
Hi, I just saw this while browsing through my timeline and I believe I know what's going on here :)

Emotion doesn't only typecheck the property names, but also their values. So this is valid:

```ts
styled.hr({borderTopStyle: 'solid'})
```

but this throws a type error:

```ts
styled.hr({borderTopStyle: 'this is not a valid value'})
```

If you pass the object directly like this, TypeScript correctly infers the type of the object to be a CSS object. But if you implicitly declare the object first

```ts
const baseStyles = {borderTopStyle: 'solid'}
const NotWorkingDivider = styled.hr(baseStyles)
```

it will just be a `{ borderTopStyle: string }` instead of emotion's css object type. To fix this I believe emotion actually exports this type that you can then explicitly assign to your objects (sorry, I'm not sure currently what that type is called and I'm not able to find it right now. I think it is something along the lines of `CSSObject`):

```ts
import { CSSObject } from "@emotion/core"

const baseStyles: CSSObject = {borderTopStyle: 'solid'}
const NowWorkingAgainDivider = styled.hr(baseStyles)
```

I of course don't know the context of this issue and perhaps you already found the solution yourself, but maybe you didn't and I was actually able to help you. Also I'm just quickly typing this up without being able to verify all this, so take it with a grain of salt :)

**Comment by kentcdodds** [comment]
Awesome! Do you know what the difference between using `CSSObject` and `Interpolation` would be in this context? Other people have been recommending `Interpolation` from `@emotion/core`

**Comment by jgierer12** [comment]
Hmm, tracing them back, the `CSSObject` comes from [frenic/csstype](https://github.com/frenic/csstype), while `Interpolation` is defined in [emotion itself](https://github.com/emotion-js/emotion/blob/master/packages/serialize/types/index.d.ts#L68-L79). It seems like `Interpolation` represents all possible arguments of `styled`, so using that is fine. On the other hand, `CSSObject` is much more strict, it pretty much only allows an object that could also be passed to vanilla JS `<div style={...} />` style prop. So it is up to you which one to use, `CSSObject` is a subset of `Interpolation`.

**Comment by kentcdodds** [comment]
Ah, that makes sense, thank you for your help @jgierer12!
